### ISSUE TITLE
Error when trying to use nvidia 5090

### ISSUE THREAD

**Issue by Roshy76** [nagadomi/nunif#308]
When trying to use my graphics card I get an error:

RuntimeError:
CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

I am running this on windows, using cpu works, but is very slow.  Would love to use my 5090.

**Comment by nagadomi** [comment]
To run on RTX5090, torch and torchvision built with CUDA 12.8 are required.
However, those official pre-built binaries for Windows are not released yet.
For Linux, it already exists in nightly build, so I think it will be released soon.
https://github.com/pytorch/pytorch/issues/146977

**Comment by djskala** [comment]
Hello, nagadomi,

First of all, thank you for the great work you do for the community.

I can confirm that the libraries for PyTorch 1.13.10 on Windows with support for CUDA 12.8 have already been released, but the issue persists. What would you recommend to make the program work correctly?

Thanks in advance!

**Comment by nagadomi** [comment]
cu128 is only available for torch 2.7. And so now it just got available.
However, it seems that torchvision cu128 is not yet available.

The installation steps are probably as follows. (obviously I haven't tried it yet)

1. open `nunif-prompt.bat`
2. `pip3 install --pre torch torchvision --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cu128`

Also note that if you run `update.bat`, torch will revert to the old(current stable) version.

**Comment by djskala** [comment]
I have already installed Torch 2.7, and the CUDA 12.8 version is also ready. However, I’m still missing torchvision. The command you suggested doesn’t work for me. Where can I check for updates on torchvision to stay up to date on its availability?  Thanks!!

**Comment by nagadomi** [comment]
The above command will not work until torchvision cu128 is released.
I don't know the workflow that nightly builds are generated by.

When `torchvision-*-cu128-cp310-cp310-win_amd64.whl` appears in https://download.pytorch.org/whl/nightly/torchvision/, it should be able to be installed.

**Comment by nagadomi** [comment]
Also unoffical builds may exist, but be careful security risk.
Do not post it here.

**Comment by nagadomi** [comment]
torchvision cu128 for Windows is now available.
The above installation command reports a numpy dependency conflict error, but I think it works fine.

You can also comment out the following line in `update.bat` with `@rem` comamnd to prevent reinstallation of the old torch.
https://github.com/nagadomi/nunif/blob/e830a9a61f187294fde9e32d8ec91b573bb16af9/windows_package/update.bat#L46
to
```
@rem python -m pip install --no-cache-dir --upgrade -r %NUNIF_DIR%\requirements-torch.txt
```

**Comment by Roshy76** [comment]
That seems to be working, thanks!  So much faster than using the cpu!

**Comment by djskala** [comment]
CUDA error: no kernel image is available for execution on the device. Compile with "TORCH_USE_CUDA_DSA" to enable device-side assertions...   :( :( :(

**Comment by djskala** [comment]
Finally got it working! Huge thanks to GROK3 from xAI for guiding me step-by-step through installing the nightly PyTorch builds (torch-2.7.0.dev20250225+cu128 and torchvision-0.22.0.dev20250226+cu128) from local .whl files and resolving dependency issues with lpips and timm. Couldn’t have done it without the detailed help!

**Comment by Better-hack** [comment]
Я использую nunif windows package https://github.com/nagadomi/nunif/blob/master/windows_package/docs/README.md
In the update.bat file:
`python -m pip install --no-cache-dir --upgrade -r "%NUNIF_DIR%\requirements-torch.txt"
if %ERRORLEVEL% neq 0 goto :on_error`
replaced it with:
`@rem python -m pip install --no-cache-dir --upgrade -r "%NUNIF_DIR%\requirements-torch.txt"
pip uninstall -y numpy
pip install numpy==1.24.3
pip install --pre torch torchvision --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cu128
if %ERRORLEVEL% neq 0 goto :on_error`
After that, everything worked.

5070 ti
