### ISSUE TITLE
Low GPU Utilization (3% or less) with RTX 4070 on Windows

### ISSUE THREAD

**Issue by musicaficionado777-ctrl** [nagadomi/nunif#456]
Hello, I am experiencing extremely low GPU utilization (3% or less) while processing video with nunif on a Windows system. This bottleneck occurs even though the GPU is correctly detected, the AI model is loaded into VRAM, and the CPU is not being bottlenecked. The performance is consistently slow, and it appears the software is not effectively leveraging the GPU's power.

This seems to be a more severe case of the "Windows performance bottleneck" that is already being discussed in this issue.

System Information:

Updated to latest version via Update.bat
Operating System: Windows 10 64bit
GPU: NVIDIA GeForce RTX 4070
NVIDIA Driver: Studio Driver (Latest version as of August 2025)
PyTorch Version: 2.7.1+cu128
CUDA Toolkit Version: 12.9

Steps Taken to Diagnose:

Confirmed torch.cuda.is_available() returns True, indicating PyTorch successfully detects and can access the GPU.
Observed GPU VRAM utilization is around 60% during processing, confirming the AI model is loaded.
Changed the video codec to h264_nvdec, which correctly offloaded video decoding from the CPU. This resulted in a drop in CPU usage, but GPU utilization did not increase.
Checked all relevant GUI settings, including Device (set to the RTX 4070), FP16 (enabled), Low VRAM (enabled), and Worker Threads (set to 8).

Key Observations:

GPU Utilization: Consistently remains at 3% or less throughout the processing task.
CPU Utilization: Remains low (around 20%), suggesting the CPU is not the bottleneck.
VRAM Usage: Stable at approximately 60%, indicating the model is ready on the GPU.

torch.compile: The torch.compile checkbox in the GUI is not grayed out, but it is unresponsive to clicks. This suggests that the software is preventing the feature from being enabled due to an internal check or error that occurs when the button is clicked, rather than a simple version check. This is a unique and potentially related symptom.

Conclusion:

This issue is likely a specific software bug related to the data transfer pipeline on Windows, and it is manifesting as both low GPU utilization and an unresponsive torch.compile button. The problem is not in a setting you can change, but in the application's code itself.

Thank you for all your hard work.

**Comment by nagadomi** [comment]
Using torch.compile on Windows requires a very complex setup, so it is normal that it does not work.
Are you using the nunif-windows package? If not using it,  please try the nunif-windows package once.
Another possible reason is slow disk speed or very high resolution video. Try placing a 1080p video on a local SSD and testing it.

**Comment by musicaficionado777-ctrl** [comment]
Hi nagadomi,

Thank you for the quick reply. 

To confirm, 

I am using the nunif-windows package.

The source video is 1080p.

The source video is on a Samsung NVMe SSD, and the output destination is a second Samsung NVMe SSD.

I have 64gb system ram too

Thanks.

**Comment by nagadomi** [comment]
Please check if Shared GPU Memory is not being used. 
Could you share a screenshot of the GUI settings screen?
What is the conversion speed in FPS?

**Comment by nagadomi** [comment]
I do not have a Windows machine with a proper GPU, so I tested it on a laptop PC with GeForce GTX 1050 Ti (a very old GPU), and it worked without any issues with Any_S.

**Comment by musicaficionado777-ctrl** [comment]
Hi nagadomi, sorry for the delay it was late and i had to sleep, I've included 3 pictures including task manager with shared GPU memory usage.

I have confirmed that the pythonw.exe process (which runs iw3) is the application using the shared GPU memory. The attached screenshot from Task Manager's "Details" tab shows 912,632 K being used by that process.

The conversion speed is consistently very slow, averaging 0.73 FPS.

![Image](https://github.com/user-attachments/assets/8dfe3489-7b9d-4aba-9d48-b274959f63b7)

![Image](https://github.com/user-attachments/assets/fe627bed-c325-423a-b3d2-76ebccd56e8c)

![Image](https://github.com/user-attachments/assets/2796309e-3c55-42c8-8891-aa127dc5ca33)

Thanks for the support.

**Comment by musicaficionado777-ctrl** [comment]
I just ran the "any_s" model with the same gui settings and get the same results as shows in the pictures above.

![Image](https://github.com/user-attachments/assets/9facbfb3-3440-4060-b628-a5b383fe6d11)

![Image](https://github.com/user-attachments/assets/20a8e967-fbb5-476d-a63e-119560974731)

![Image](https://github.com/user-attachments/assets/97b537bc-f8e2-4b83-91c4-7f0dd1f39dfc)

**Comment by nagadomi** [comment]
The slow conversion is probably caused by Depth Resolution being too high and TTA being enabled. Edge Fix is also an unusual setting.

1. Set Depth Resolution to Default, or to 518 for high-resolution setting. See https://github.com/nagadomi/nunif/discussions/168
2. Turn off TTA. 
3. Set Edge Fix to 2

Also, `Any_V2_K_*` is trained with car interior view, so it is not suitable for general videos.
If the settings are unclear, start from the default settings. Deleting `nunif\tmp\iw3-gui.cfg` will reset to default.
Also, for videos with multiple scenes, turning on `Scene Boundary Detection` is recommended.

The low GPU usage is probably due to Task Manager on Windows not showing CUDA usage correctly.
https://michaelceber.medium.com/gpu-monitoring-on-windows-10-for-machine-learning-cuda-41088de86d65

If there is no "CUDA" option under "3D" in Task Manager, please check using nvidia-smi or another tool.

**Comment by nagadomi** [comment]
Regarding Shared GPU Memory, on Windows it starts being used when VRAM runs out, which causes a dramatic slowdown. However, how exactly the Windows driver behaves is unclear, and some use of shared memory may occur even before VRAM is full.
If this is suspected as the cause, try closing the application or restarting the system. Fundamentally, this happens when VRAM usage is too high.
Related to https://github.com/nagadomi/nunif/discussions/285

**Comment by musicaficionado777-ctrl** [comment]
OK, Thanks for the tips. I was hoping to get better speed and hardware utilization at higher depth resolutions as the the results look much better IMO. I thought id post the results with your settings recommendations here also just for reference as speed and utilization has improved but im still only getting 26 - 27% gpu core utilization. Thank you.

![Image](https://github.com/user-attachments/assets/a6e48126-79d7-4446-8328-2a736eb58f74)

![Image](https://github.com/user-attachments/assets/d52a84b2-5669-454a-81ba-43363af7d62b)

![Image](https://github.com/user-attachments/assets/b3a2259f-88d2-4904-b42f-4fb6cd7c5e45)

**Comment by nagadomi** [comment]
Uncheck Low VRAM. When it is enabled, Batch Size and Worker Threads are internally forced to 1 and 0, ignoring the user's settings.

Also, 23% shows the usage of the NVIDIA Encoder (video encoding chip), and CUDA/Tensor core usage may not be shown in Task Manager.

**Comment by nagadomi** [comment]
Open `Command Prompt` and run `nvidia-smi -lms 1000` command to show GPU usage every second.

**Comment by diverswan9** [comment]
@musicaficionado777-ctrl ... you might also try with "Stream" unchecked. Try 'batch' 4 and 'threads' 2.

**Comment by nagadomi** [comment]
"Low GPU utilization" is a misunderstanding caused by Window Task Manager not showing GPU usage correctly.
In general, image processing time depends on the area, so it is normal that 1600x1600 is about 10x slower than 518x518.

**Comment by kuumottaja** [comment]
I noticed that enabling Hardware-accelerated GPU scheduling allows Task Manager to display GPU core usage correctly, but CUDA utilization values are no longer reported.
